### ISSUE TITLE
The way of authentication

### ISSUE THREAD

**Issue by CUHKJason** [Mr-Un1k0d3r/SCShell#1]
Hi everyone, may I know if it is a must to use plaintext password to perform authentication over DCERPC? Can I also do pass-the-hash?

**Comment by Mr-Un1k0d3r** [comment]
Yes pass the hash may be possible but it will required quite a lot of code. What I can do it reimplement it using a higher level language such as python and create a pass the hash option. I could make a pull request and add it to the impacket suite.

**Comment by omriman067** [comment]
If you could do that it would be wonderfull :) 
I'm sure there will be much potential for it, considering it uses a single DCERPC ntlm authentication.
